from django.conf.urls import url
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from . import views

urlpatterns = [
    path('getProgressionList/',
         views.ListFeatureProgression.as_view(),
         name='progressions'),
    path('getStudentList/<int:progression_pk>/',
         views.ListFeatureStudent.as_view(),
         name='students'),
    path('getStudentListExtended/<int:progression_pk>/',
         views.ListStudentCurriculum.get_students_curriculum_details,
         name='students_belt'),
    path('getStudentCurriculumList/<int:progression_pk>/<int:student_pk>/',
         views.FeatureProgressionGeneric.get_students_curriculum,
         name='students_curriculum'),
    path('getChallengesByStudentsCurriculumList/<int:student_pk>/<int:progression_pk>/<int:curriculum_pk>/',
         views.FeatureProgressionGeneric.get_students_challenge,
         name='challenge'),
    path('progression_students/<int:student_pk>/<int:challenge_pk>/',
         views.FeatureProgressionGeneric.get_students_challenge_details,
         name='challenge_status'),
    path('students',
         views.ListFeatureStudent.as_view(),
         name='students'),
    path('getChallengeTypeList/',
         views.ListChallengeTypes.as_view(),
         name='challenge_types'),
    path('update_challenge_status/',
         views.FeatureProgressionGeneric.update_challenge_status,
         name='update_challenge_status'),
    path('update_video_url/',
         views.FeatureProgressionGeneric.update_video_url,
         name='update_video_url'),
    path('update_student_challenge_video_url/',
         views.FeatureProgressionGeneric.update_student_challenge_video_url,
         name='update_student_challenge_video_url'),
    path('getUser/',
         views.UserGeneric.as_view(),
         name='current_user'),
    path('sign_s3_upload/<str:object_name>/<int:insrtuctor_id>/<int:student_id>/<int:curriculum_id>/<int:challenge_id>/<int:progression_id>/',
         views.S3Service.sign_s3_upload,
         name='sign_s3_upload'),
    path('update_student_photo/<int:student_id>/',
         views.FeatureStudentGeneric.update_student_photo,
         name='update_student_photo'),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
    url(r'^users/register/', views.CreateUserView.as_view()),
    url(r'^instructor/register/', views.CreateInstructorView.as_view()),
]